BiliV/models/Barrage.py
'''from BiliV.foundation import db

class Barrage(db.Model):
	__tablename__ = "barrage"
	  
	id = db.Column(db.Integer, primary_key=True)
	avid = db.Column(db.Integer, db.ForeignKey('video.id'), nullable = False)
	#fbid = Column(Integer, ForeignKey('bili_user.mid'), nullable = False)
	text = db.Column(db.String(300)) # according to wikipedia
	second = db.Column(db.Float)
	mode = db.Column(db.Integer)
	font_size = db.Column(db.Float)
	color = db.Column(db.Integer)
	timestamp = db.Column(db.Integer)
	pool = db.Column(db.Integer)
	owner = db.Column(db.String(30), nullable = False)
	rowid = db.Column(db.Integer)
'''

BiliV/models/Idfvoc.py
#! encoding=utf-8

from BiliV.foundation import db_session, Base
from sqlalchemy import Column, Integer, Float, String

class Idfvoc(Base):
	__tablename__ = 'idfvoc'
	__table_args__ = {
			'mysql_engine': 'InnoDB',
			'mysql_charset': 'utf8mb4'
	}
	word = Column(String(20), primary_key = True)
	idf = Column(Float)

BiliV/models/Video.py
#! encoding=utf-8

from BiliV.foundation import db_session, Base
from sqlalchemy import Column, Integer, ForeignKey, String, Text, Float, LargeBinary, DateTime
from sqlalchemy.dialects.mysql import TINYINT

class Video(Base):
	__tablename__ = "bilibili_video_info"

	id = Column(Integer, primary_key = True)
	url = Column(String(100))
	play = Column(Integer)
	date = Column(DateTime)
	title = Column(String(100))
	author = Column(String(100))
	description = Column(Text)
	pic = Column(String(100))
	pts = Column(String(10))
	videotype = Column(String(10))
	detail = Column(Text)
	isempty = Column(String(24))
	hasempty = Column(String(1))
	isnew = Column(String(1))
	flushtime = Column(DateTime)

BiliV/models/WeiboTweet.py
from datetime import datetime
from BiliV.foundation import db_session, Base
from sqlalchemy import Column, Integer, String, DateTime, Text, BigInteger, UnicodeText, Unicode
from sqlalchemy.orm import relationship
from sqlalchemy import ForeignKey
from sqlalchemy_utils import JSONType
from WeiboVideo import WeiboVideo
from WeiboUser import WeiboUser

class WeiboTweet(Base):
	__tablename__ = 'biliv_weibo_tweet'
	__table_args__ = {
	  "mysql_engine": 'InnoDB',
	  "mysql_charset": 'utf8mb4'
	}
	id = Column(BigInteger, primary_key = True)
	uid = Column(BigInteger, ForeignKey('biliv_weibo_user.id'))
	created_at = Column(DateTime)
	utc = Column(String(10))
	text = Column(UnicodeText)
	source = Column(String(50))
	reposts_cnt = Column(Integer)
	comments_cnt = Column(Integer)
	data_set = Column(JSONType)    #all weibo API data

	flag = Column(Integer, default = 0)
	state = Column(Integer, default = 0)

	root_id = Column(BigInteger, default = 0)
	images = Column(Text, default='[]')
	video_id = Column(Integer, ForeignKey('weibo_video.id'))
	video = relationship(WeiboVideo, primaryjoin = video_id == WeiboVideo.id)
	user = relationship(WeiboUser, primaryjoin = uid == WeiboUser.id)

	def __str__(self):
		return self.id

	def __repr__(self):
		return "<Weibo %r>" % self.text

BiliV/models/WeiboUser.py
from BiliV import const
from BiliV.foundation import db_session, Base
from sqlalchemy import Column, Integer, String, DateTime, Text, BigInteger, ForeignKey, UnicodeText, Unicode
from sqlalchemy.orm import relationship, backref
from sqlalchemy_utils import ArrowType, JSONType
from SNS import sina
from flask.ext.login import UserMixin
import arrow

def analyze_gender(gender):
	m = {
		"m": const.GENDER_MALE,
		"f": const.GENDER_FEMALE,
	}
	return m.get(gender, const.GENDER_NONE)

class RecommendRelation(Base):
	__tablename__ = 'recommend_relation'
	__table_args__ = {
		'mysql_engine': 'InnoDB',
		'mysql_charset': 'utf8mb4'
	}
	id = Column(Integer, primary_key = True)
	bili_video_id = Column(Integer, ForeignKey('bilibili_video_info.id'))
	weibo_user_id = Column(BigInteger, ForeignKey('biliv_weibo_user.id'))
	algorithm = Column(String(50))

class LikeRelation(Base):
	__tablename__ = 'like_relation'
	__table_args__ = {
			'mysql_engine': 'InnoDB',
			'mysql_charset': 'utf8mb4'
	}
	id = Column(Integer, primary_key = True)
	video_id = Column(Integer, ForeignKey('bilibili_video_info.id'))
	weibo_user_id = Column(BigInteger, ForeignKey('biliv_weibo_user.id'))
	score = Column(Integer, default = 0)

class WeiboRelation(Base):
	__tablename__ = 'biliv_weibo_relation'
	__table_args__ = {
	  "mysql_engine": 'InnoDB',
	  "mysql_charset": 'utf8mb4'
	}
	id = Column(Integer, primary_key = True)
	follower_id = Column(BigInteger, ForeignKey('biliv_weibo_user.id'))
	followed_id = Column(BigInteger, ForeignKey('biliv_weibo_user.id'))

class WeiboUser(Base, UserMixin):
	__tablename__ = 'biliv_weibo_user'
	__table_args__ = {
		"mysql_engine": "InnoDB",
		"mysql_charset": "utf8mb4"
	}
	id = Column(BigInteger, primary_key = True)

	access_token = Column(String(100))
	expire_date = Column(ArrowType)

	last_update = Column(ArrowType)

	screen_name = Column(Unicode(50))
	description = Column(Unicode(100))
	gender = Column(Integer)
	image_url = Column(String(100))
	followers_cnt = Column(Integer)
	friends_cnt = Column(Integer)
	statuses_cnt = Column(Integer)
	bi_followers_cnt = Column(Integer)
	cute = Column(Integer)
	hot = Column(Integer)
	liter = Column(Integer)
	wierd = Column(Integer)
	aj = Column(Integer)
	otaku = Column(Integer)
	fu = Column(Integer)
	flag = Column(Integer, default = 0)
	state = Column(Integer, default = 0)
	detail = Column(JSONType)    #all weibo json data

	followed = relationship('WeiboUser', secondary = WeiboRelation.__table__, primaryjoin = (WeiboRelation.follower_id == id), secondaryjoin = (WeiboRelation.followed_id == id), backref = backref('WeiboRelation', lazy = 'dynamic'), lazy = 'dynamic')
	like_videos = relationship('Video', secondary=LikeRelation.__table__, backref=backref('biliv_weibo_users', lazy='dynamic'))
	biliv_recommend_videos = relationship('Video', secondary=RecommendRelation.__table__, backref=backref('biliv_weibo_users_recommend', lazy='dynamic'))

	def __repr__(self):
		return "<User %r>" % self.screen_name

	def update_token(self, data):
		"""Store access token and expire date returning by WeiboAPI"""
		self.access_token = data['access_token']
		date = arrow.Arrow.fromtimestamp(data['expires_in'])
		self.expire_date = date
		return

	def update(self):
		api = sina.WeiboAPI(self.access_token, self.id)

		data = api.get_user_data()

		self.screen_name = data['screen_name']
		self.description = data['description']
		self.gender = analyze_gender(data['gender'])
		self.image_url = data['profile_image_url']
		self.followers_cnt = data['followers_count']
		self.friends_cnt = data['friends_count']
		self.statuses_cnt = data['statuses_count']
		self.bi_followers_cnt = data['bi_followers_count']

		self.detail = data
		self.last_update = arrow.utcnow()

BiliV/models/WeiboVideo.py
from BiliV.foundation import db_session, Base
from sqlalchemy import Column, Integer, String, DateTime, Text, BigInteger, UnicodeText, Unicode
from sqlalchemy.orm import relationship
from sqlalchemy import ForeignKey
from sqlalchemy_utils import JSONType

class WeiboVideo(Base):
	__tablename__ = 'weibo_video'
	__table_args__ = {
	  "mysql_engine": 'InnoDB',
	  "mysql_charset": 'utf8mb4'
	}

	id = Column(Integer, primary_key = True)
	platform = Column(String(10))

	title = Column(UnicodeText)
	brief = Column(UnicodeText)

	url = Column(Text)
	other = Column(JSONType)

	seg_info = Column(JSONType)
	state = Column(Integer, default = 0)

BiliV/models/__init__.py
from .WeiboUser import WeiboUser, WeiboRelation, RecommendRelation, LikeRelation
from .WeiboTweet import WeiboTweet
#from .Friends import Friends
from .Video import Video
from .Idfvoc import Idfvoc

BiliV/__init__.py
from flask import Flask, g, session, redirect, json, url_for, render_template
from flask.ext.login import current_user
from BiliV import views
from BiliV.foundation import login_manager, db_session
from BiliV.models import WeiboUser

DEFAULT_MODULES = [
	views.frontend,
	views.account,
	views.play,
#	views.discover
]

def create_app():
	app = Flask(__name__)
	app.config.from_object('config')
	configure_foundations(app)
	configure_blueprint(app, DEFAULT_MODULES)
	configure_template_filter(app)
	return app

def configure_foundations(app):
	#db.app = app
	#db.init_app(app)
	@app.after_request
	def releaseDB(response):
		db_session.remove()
		return response
	login_manager.init_app(app)
	login_manager.login_view = 'frontend.login'
	login_manager.login_message_category = "info"
	@login_manager.user_loader
	def load_user(id):
		try:
			return WeiboUser.query.get(int(id))
		except Exception:
			return None
	@app.before_request
	def before_request():
		g.user = current_user
		return

def configure_blueprint(app, modules):
	for module in modules:
		if module.name == "frontend":
			app.register_blueprint(module)
		else:
			app.register_blueprint(module, url_prefix="/%s" % (module.name))

def configure_template_filter(app):
	@app.template_filter('dateint')
	def _jinja2_filter_dateint(dateint):
		return date.fromordinal(dateint).strftime('%Y-%m-%d')

BiliV/algorithm/__init__.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

BiliV/controller/__init__.py
#! encoding=utf-8

BiliV/views/__init__.py
from .frontend import frontend
from .account import account
from .play import play
#from .discover import discover

BiliV/views/account.py
#! encoding=utf-8
from flask import Blueprint, render_template, request, redirect, url_for, g
from flask.ext.login import login_required
from BiliV.foundation import Base, db_session
from BiliV.models import Video, WeiboUser, LikeRelation, Idfvoc
import BiliV.redisconfig as rc
import redis as redis_connect
import BiliV.const

account = Blueprint('account', __name__, template_folder = 'template')

@account.route('/', methods = ['GET', 'POST'])
@login_required
def index():
	user = g.user
	like_list = LikeRelation.query.filter_by(weibo_user_id = g.user.id).filter_by(score = 3).all()
	likes = list()
	for l in like_list:
		v = Video.query.filter_by(id = l.video_id).first()
		likes.append(v)
	r = redis_connect.Redis(host = rc.DATA_REDIS_HOST, port = rc.DATA_REDIS_PORT, db = rc.DATA_USER_SPARSE_TFIDF_DB)
	key_tuples = r.lrange(g.user.id, 0, 10)
	words = Idfvoc.query.all()
	key_words = dict()
	for tp in key_tuples:
		tp = tp[1 : -1]
		tp_list = tp.split(',')
		word_num = int(tp_list[0].strip()) 
		weight = float(tp_list[1].strip())
		word = words[word_num].word
		key_words[word] = weight
		print "here"
		print key_words
	return render_template('account/account.html', key_words = key_words, likes = likes)

@account.route('/edit_interests', methods = ['GET', 'POST'])
@login_required
def edit_interests():
	return render_template('account/waiting.html')

BiliV/views/frontend.py
#! encoding=utf-8
from flask import Blueprint, render_template, redirect, request, url_for, g
from sqlalchemy import desc
from BiliV.foundation import Base, db_session
from BiliV.models import Video, WeiboUser, RecommendRelation
from BiliV.algorithm import algorithm
from BiliV.controller import video, get_recommend_video, get_weibo, friends
from flask.ext.login import login_user, logout_user, login_required
from BiliV import const
from SNS import sina
import arrow, random
import os

frontend = Blueprint('frontend', __name__, template_folder = 'templates')

@frontend.route('/', methods=['GET', 'POST'])
@login_required
def index():
	#get_weibo.get_weibo_data(g.user.access_token, g.user.id)
	#friends.get_friends_data(g.user.access_token, g.user.id)
	#user = WeiboUser.query.filter_by(id=g.user.id).first()
	video_type = request.args['type']
	common_videos = list()
	if video_type=='rand':
		all_videos = Video.query.all()
		common_videos = common_videos + random.sample(all_videos, 30)
	elif video_type=='visitsort':
		common_list = RecommendRelation.query.filter_by(weibo_user_id = g.user.id).filter_by(algorithm = 'VisitSort').all()
		for cl in common_list:
			v = Video.query.filter_by(id = cl.bili_video_id).first()
			common_videos.append(v)
	elif video_type=='tfidf':
		common_list = RecommendRelation.query.filter_by(weibo_user_id = g.user.id).filter_by(algorithm = 'docmatching').all()
		for cl in common_list:
			v = Video.query.filter_by(id = cl.bili_video_id).first()
			common_videos.append(v)
	elif video_type == 'lda':
		common_list = RecommendRelation.query.filter_by(weibo_user_id = g.user.id).filter_by(algorithm = 'ldamatching').all()
		for cl in common_list:
			v = Video.query.filter_by(id = cl.bili_video_id).first()
			common_videos.append(v)
	elif video_type=='wierd':
		common_videos = video.show_video_data(10, u'鬼畜')
	important_videos = list()
	if len(common_videos) != 0:
		important_videos = common_videos[:10]
		important_videos = random.sample(important_videos, 2)
		for v in important_videos:
			common_videos.remove(v)
	#common_videos = random.sample(common_videos, 8)
	return render_template('frontend/index.html', important_videos = important_videos, common_videos = common_videos)

@frontend.route('/login')
def login():
	if g.user is not None and g.user.is_authenticated():
		return redirect(url_for('.index', type='all'))
	auth = sina.WeiboOAuth(const.APP_KEY, const.APP_SECRET)
	authorize_url = auth.get_auth_url(const.CALLBACK_URL)
	videos_list = RecommendRelation.query.filter_by(algorithm='VisitSort').all()
	videos = list()
	for v in videos_list:
		video = Video.query.filter_by(id = v.bili_video_id).first()
		if video not in videos:
			videos.append(video)
	videos = random.sample(videos, 8)
	return render_template('frontend/login.html', authorize_url = authorize_url, videos = videos)

@frontend.route('/logout')
@login_required
def logout():
	logout_user()
	return redirect(url_for('.login'))

@frontend.route('/callback', methods = ['GET', 'POST'])
def callback():
	try:
		code = request.args['code']
		api = sina.WeiboOAuth(const.APP_KEY, const.APP_SECRET)

		tokens = api.exchange_access_token(const.CALLBACK_URL, code)

		# assumpt uid in tokens...
		uid = int(tokens['uid'])
		user = WeiboUser.query.get(uid)
		#return user.id
		need_fetch = True
		if user is None:
			user = WeiboUser(id=uid)
			db_session.add(user)
		else:
			limit = arrow.utcnow().replace(hours=-1)
			if user.last_update and user.last_update > limit:
				need_fetch = False
		user.update_token(tokens)
		#Need to add command
		if need_fetch:
			user.update()
			get_weibo.get_weibo_data(user.access_token, user.id)
			db_session.commit()
		login_user(user)
		return redirect(url_for('.index', type='all'))
	except:
		raise
		db_session.rollback()
		return render_template('frontend/error.html')

@frontend.route('/hot')
def hot():
	auth = sina.WeiboOAuth(const.APP_KEY, const.APP_SECRET)
	authorize_url = auth.get_auth_url(const.CALLBACK_URL)
	videos_list = RecommendRelation.query.filter_by(algorithm='VisitSort').all()
	videos = list()
	for v in videos_list:
		video = Video.query.filter_by(id = v.bili_video_id).first()
		if video not in videos:
			videos.append(video)
	videos = random.sample(videos, 16)
	return render_template('frontend/hot.html', authorize_url = authorize_url, videos = videos)

@frontend.route('/like_post/<video_id>', methods = ['GET', 'POST'])
def like_post(video_id):
	print video_id
	videos = LikeRelation.query.filter_by(video_id = video_id).all()
	like_relation = videos.query.filter_by(weibo_user_id = g.user.id).first()
	if like_relation is None:
		like_relation = LikeRelation(video_id = video_id, weibo_user_id = g.user.id, score = 3)
		db.session.add(like_relation)
		db.session.commit()
	else:
		db.session.delete(like_relation)
		db.session.commit()

BiliV/views/play.py
#! encoding=utf-8
from flask import Blueprint, render_template, redirect, request, url_for, g
from BiliV.foundation import Base, db_session
from flask.ext.login import login_required
from BiliV.controller import video
from BiliV.models import Video, WeiboUser, LikeRelation
from BiliV import const

play = Blueprint('play', __name__, template_folder = 'template')

@play.route('/', methods = ['GET', 'POST'])
def index():
	aid = request.args.get('aid')
	play_video = Video.query.filter_by(id = aid).first()
	if play_video is None:
		return render_template('frontend/error.html')
	cur_play = LikeRelation.query.filter_by(weibo_user_id = g.user.id).filter_by(video_id = aid).first()
	if cur_play is None:
		cur_play = LikeRelation(weibo_user_id = g.user.id, video_id = aid)
		db_session.add(cur_play)
	if cur_play.score is None:
		cur_play.score = const.PLAY
	db_session.commit()
	recommend_videos = video.show_video_data(6, u'')
	return render_template('play/play.html', video = play_video, recommend_videos=recommend_videos)

@play.route('/like_video', methods = ['GET', 'POST'])
@login_required  
def like_video():
	aid = request.args.get('aid')
	user = g.user
	video = Video.query.filter_by(id = aid).first()
	cur_play = LikeRelation.query.filter_by(weibo_user_id = g.user.id).filter_by(video_id = aid).first()
	if cur_play is None:
		cur_play = LikeRelation(weibo_user_id = g.user.id, video_id = aid)
		db_session.add(cur_play)
	cur_play.score = const.LIKE
	db_session.commit()
	return redirect(url_for('.index', aid = aid))

@play.route('/dislike_video', methods = ['GET', 'POST'])
@login_required  
def dislike_video():
	aid = request.args.get('aid')
	user = g.user
	video = Video.query.filter_by(id = aid).first()
	cur_play = LikeRelation.query.filter_by(weibo_user_id = g.user.id).filter_by(video_id = aid).first()
	if cur_play is None:
		cur_play = LikeRelation(weibo_user_id = g.user.id, video_id = aid)
		db_session.add(cur_play)
	cur_play.score = const.DISLIKE
	db_session.commit()
	return redirect(url_for('.index', aid = aid))

BiliV/views/user.py
from flask import Blueprint, render_template, url_for, g
from BiliV.foundation import db
from BiliV.models.User import User
from flask.ext.login import login_required

user = Blueprint('user', __name__)

@user.route()

BiliV/templates/base.html
{% extends "bootstrap_base.html" %}
{% block body_content %}
{% if g.user and g.user.is_authenticated() %}
{% block head_navbar %}
<nav class="header navbar navbar-default navbar-fixed-top " role="navigation">
<div class="container">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
			<a class="header-logo" href="{{url_for('frontend.index', type='rand')}}"></a>
	</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav nav-tabs" role="tablist" id="type-tab">
				<li><a href="{{url_for('frontend.index', type='rand')}}" role="tab">随机算法</a></li>
				<li><a href="{{url_for('frontend.index', type='visitsort')}}" role="tab">热度</a></li>
				<li><a href="{{url_for('frontend.index', type='tfidf')}}" role="tab">TF-IDF</a></li>
				<li><a href="{{url_for('frontend.index', type='lda')}}" role="tab">LDA</a></li>
				<li><a href="{{url_for('frontend.index', type='wierd')}}" role="tab">鬼畜</a></li>
				<li><a href="#" role="tab">发现</a></li>
			
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img class="circle-img" width="50px" height="50px" src="{{g.user.image_url}}">
					<span class="name">{{g.user.screen_name}}</span></a>
					<ul class="dropdown-icon dropdown-menu user-menu" role="menu">
					  <li><a href="{{url_for('account.index')}}">My Homepage</a></li>
					<li><a href="{{url_for('frontend.logout')}}">Log out</a></li>
				  </ul>
				</li>
			</ul>
			<!--likes/deletes/refresh-->
		  <ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
			   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				<button type="button" class="btn btn-icon" aria-label="Left Align">
				<span class="fa fa-heart" aria-hidden="true"></span>
				</button><span id="like-counts">0</span></a>

				<ul class="dropdown-menu dropdown-icon" role="menu">
				<li><div><h5><a href="play.html">白日梦想家</a></h5></div>
				<li><div><h5><a href="#">夏目友人帐</a></h5></div></li>
				<li><div><h5><a href="#">奥斯卡最佳电影【聚焦】</a></h5></div></li>
				<li><div><h5><a href="#">蜡笔小新</a></h5></div></li>
				<li><div><h5><a href="#">校园迷糊大王</a></h5></div></li>
				<li><div><h5><a href="#">独特中国味</a></h5></div></li>
				<li><div class="center-link"><h5><a href="user.html#likes">查看全部 »</a></h5></div></li>
			  </ul>
			</li>
			<li>
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				<button type="button" class="btn btn-icon" aria-label="Left Align">
				<span class="fa fa-trash" aria-hidden="true"></span>
				</button><span id="unlike-counts">0</span></a>
				<ul class="dropdown-menu dropdown-icon" role="menu">
				<li><div><h5><a href="play.html">白日梦想家</a></h5></div>
				<li><div><h5><a href="#">夏目友人帐</a></h5></div></li>
				<li><div><h5><a href="#">奥斯卡最佳电影【聚焦】</a></h5></div></li>
				<li><div><h5><a href="#">蜡笔小新</a></h5></div></li>
				<li><div><h5><a href="#">校园迷糊大王</a></h5></div></li>
				<li><div><h5><a href="#">独特中国味</a></h5></div></li>
			  </ul>
			</li>
			<li><a href="#" class="dropdown-toggle" data-toggle="dropdown">
				<button type="button" class="btn btn-icon" aria-label="Left Align">
				<span class="fa fa-refresh" aria-hidden="true"></span></button>
				</a>
			</li>
		  </ul>

	  </div><!-- /.container-fluid -->
</nav>
{% endblock %}
{% endif %}
{% endblock %}

BiliV/templates/bootstrap_base.html
<!DOCTYPE html>
<html{% block html_attribs %} lang="zh-CN"{% endblock %}>
	{% block html %}
	<head>
		{% block head %}
			<meta charset="UTF-8">
			{% block meta %}
				<meta http-equiv="X-UA-Compatible" content="IE=edge">
			{% endblock %}
			<title>{% block title %}{{title}}{% endblock %}</title>
			{% block style %}
				<link rel=stylesheet href="{{url_for('static', filename='css/reset.css')}}">
				<link rel=stylesheet href="{{url_for('static', filename='css/bootstrap.min.css')}}">
			{% endblock %}
			{% block script %}
				<script src="{{url_for('static', filename='js/libs/jquery/jquery.js')}}"></script>
				<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
			{% endblock %}
		{% endblock %}
	</head>
	
	<body>
		{% block body %}
			<div class="container">
			{% block body_content %}
			{% endblock %}
			</div>	
		{% endblock %}
	</body>
	{% endblock %}
</html>